The only solution that worked for me is to manually activate the main (the one containing mlflow as a dependency, not the steps) mlflow-* environment (created by mlflow, mlflow-39beb38945f7e5378bc314f1ee9f6f4b4376524a in my case) having the error and installing numpy version 1.23.4 in it (pip install numpy==1.23.4) as recommended by this StackOverflow thread!

- https://stackoverflow.com/questions/75621657/how-to-fix-np-object-will-be-defined-as-the-corresponding-numpy-scalar-in-kera
