The only solution that worked for me is to manually activate the main (the one containing mlflow as a dependency, not the steps) mlflow-* environment (created by mlflow, mlflow-39beb38945f7e5378bc314f1ee9f6f4b4376524a in my case) having the error and installing numpy version 1.23.4 in it (pip install numpy==1.23.4) as recommended by this StackOverflow thread!

- https://stackoverflow.com/questions/75621657/how-to-fix-np-object-will-be-defined-as-the-corresponding-numpy-scalar-in-kera


to fix PermissionError: [Errno 13] Permission denied: 'outputs/2023-07-24/12-24-22'
you need to change the ownership of the corresponding folder/file to the current user
https://askubuntu.com/questions/6723/change-folder-permissions-and-ownership

$ ll
drwxr-xr-x  4 root    root     4096 Jul 24 09:49 outputs/
$ sudo chown -R $USER outputs/
$ ll
drwxr-xr-x  4 m-sahli root     4096 Jul 24 09:49 outputs/



